#ifndef PARSER_CONFIG_H
#define PARSER_CONFIG_H

/**
 * COMPILE-TIME CONFIGURATION FOR PARSER
 */

#include "macro.h"

#define PARSE_CONFIG(SETTING) PRIMITIVE_CAT(PARSE_CONFIG_, SETTING)

#define PARSE_CONFIG_ERROR_ON_UNRECOGNIZED_ESCAPED_SEQUENCE 1
#define PARSE_CONFIG_IGNORE_NONPRINTABLE_REGEX_CHAR 0
#define PARSE_CONFIG_TREAT_UNEXPECTED_TOKENS_AS_ESCAPED 0

#endif