#include "parser/parser.h"

typedef enum grammar_symbols
{
    SYM_BASIC_SYMBOL,
    SYM_ESCAPED_SYMBOL, 
    SYM_CLASS_SYMBOL,
    SYM_NUMBER,
    SYM_LPAREN,
    SYM_RPAREN,
    SYM_LBRACKET,
    SYM_RBRACKET,
    SYM_LBRACE,
    SYM_RBRACE,
    SYM_ASTERISK,
    SYM_PLUS,
    SYM_QUESTION,
    SYM_COMMA,
    SYM_UNION,
    SYM_MINUS,
    SYM_END,
    SYM_REGEX,
    SYM_SYMBOL,
    SYM_SIMPLE_SYMBOL,
    SYM_ALT_TERMS,
    SYM_ALT_TERM,
    SYM_ALT_TERM_PRIME,
    SYM_CONCAT_TERM,
    SYM_CONCAT_TERM_PRIME,
    SYM_DUP_TERM,
    SYM_DUP_TERM_PRIME,
    SYM_DUP_RANGE,
    SYM_DUP_RANGE_PRIME,
    SYM_GROUP_TERM,
    SYM_BRACKET_SYMBOL,
    SYM_BRACKET_SYMBOL_PRIME,
    SYM_BRACKET_LIST,
    SYM_BRACKET_LIST_PRIME,
    SYM_BRACKET_TERM,
    SYM_TOTAL_GRAMMAR_SYMBOLS    
} GRAMMAR_SYMBOL;

#define IS_TERMINAL(sym) ((sym) >= SYM_BASIC_SYMBOL && (sym) <= SYM_END)
#define IS_NONTERMINAL(sym) ((sym) >= SYM_REGEX && (sym) <= SYM_BRACKET_TERM)

