name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt install libcriterion-dev
    - name: make
      run: make all
  test:
    runs-on: ubuntu-latest
    steps:
    - name: run_tests
      run: ./bin/regex_tests

